from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 348)
        MainWindow.setMinimumSize(QtCore.QSize(251, 348))
        MainWindow.setMaximumSize(QtCore.QSize(251, 348))
        MainWindow.setSizeIncrement(QtCore.QSize(250, 348))
        font = QtGui.QFont()
        font.setPointSize(6)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 251, 351))
        self.main_frame.setMinimumSize(QtCore.QSize(251, 351))
        self.main_frame.setMaximumSize(QtCore.QSize(251, 351))
        self.main_frame.setStyleSheet("background-color: rgb(46, 204, 194);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.board_frame = QtWidgets.QFrame(self.main_frame)
        self.board_frame.setGeometry(QtCore.QRect(0, 60, 251, 251))
        self.board_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.board_frame.setObjectName("board_frame")
        self.frame_3 = QtWidgets.QFrame(self.board_frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 231, 231))
        self.frame_3.setStyleSheet("background-color: rgb(143, 143, 143);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(46, 204, 194);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.x_o_result_frame = QtWidgets.QFrame(self.main_frame)
        self.x_o_result_frame.setGeometry(QtCore.QRect(0, 0, 261, 41))
        self.x_o_result_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_o_result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.x_o_result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.x_o_result_frame.setObjectName("x_o_result_frame")
        self.x_result_label = QtWidgets.QLabel(self.x_o_result_frame)
        self.x_result_label.setGeometry(QtCore.QRect(10, 0, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.x_result_label.setFont(font)
        self.x_result_label.setObjectName("x_result_label")
        self.o_result_label = QtWidgets.QLabel(self.x_o_result_frame)
        self.o_result_label.setGeometry(QtCore.QRect(170, 0, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.o_result_label.setFont(font)
        self.o_result_label.setObjectName("o_result_label")
        self.x_result_label_2 = QtWidgets.QLabel(self.x_o_result_frame)
        self.x_result_label_2.setGeometry(QtCore.QRect(70, 0, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.x_result_label_2.setFont(font)
        self.x_result_label_2.setStyleSheet("color: rgb(145, 145, 145);")
        self.x_result_label_2.setObjectName("x_result_label_2")
        self.x_result_label_3 = QtWidgets.QLabel(self.x_o_result_frame)
        self.x_result_label_3.setGeometry(QtCore.QRect(230, 0, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.x_result_label_3.setFont(font)
        self.x_result_label_3.setStyleSheet("color: rgb(145, 145, 145);")
        self.x_result_label_3.setObjectName("x_result_label_3")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setGeometry(QtCore.QRect(0, 310, 251, 41))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.restart_button = QtWidgets.QPushButton(self.frame)
        self.restart_button.setGeometry(QtCore.QRect(60, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.restart_button.setFont(font)
        self.restart_button.setStyleSheet("color: rgb(42, 144, 136);")
        self.restart_button.setObjectName("restart_button")
        self.frame_2 = QtWidgets.QFrame(self.main_frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 251, 21))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(120, 0, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(145, 145, 145);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setText(_translate("MainWindow", "X"))
        self.pushButton_7.setText(_translate("MainWindow", "O"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
        self.pushButton_5.setText(_translate("MainWindow", "X"))
        self.pushButton.setText(_translate("MainWindow", "O"))
        self.pushButton_4.setText(_translate("MainWindow", "X"))
        self.pushButton_9.setText(_translate("MainWindow", "O"))
        self.pushButton_6.setText(_translate("MainWindow", "O"))
        self.x_result_label.setText(_translate("MainWindow", "x "))
        self.o_result_label.setText(_translate("MainWindow", "o"))
        self.x_result_label_2.setText(_translate("MainWindow", "-"))
        self.x_result_label_3.setText(_translate("MainWindow", "-"))
        self.restart_button.setText(_translate("MainWindow", "RESTART GAME"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label.setText(_translate("MainWindow", "Turn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
